// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfohpwclpbfxftgfolwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmb2hwd2NscGJmeGZ0Z2ZvbHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTU4NjcsImV4cCI6MjA3Mzg3MTg2N30.Ptnf5-ZtoFCXoWoULFCIewY1WO-x6gh3CMB1v8GM6rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});